create or replace view EXERCISE_CO2_VS_TEMPERATURE.PSA.STG_EMISSIONS_BY_COUNTRY(
    ANNUAL_CO2_EMISSIONS,
    ANNUAL_CO2_GROWTH_PERCENTAGE,
    ANNUAL_CO2_GROWTH_ABS,
    ANNUAL_CONSUMPTION_BASED_CO2_EMISSIONS,
    CO2_EMISSIONS_EMBEDDED_IN_TRADE,
    CO2_EMISSIONS_FROM_BUNKERS,
    CO2_EMISSIONS_FROM_CEMENT,
    CO2_EMISSIONS_FROM_COAL,
    CO2_EMISSIONS_FROM_FLARING,
    CO2_EMISSIONS_FROM_GAS,
    CO2_EMISSIONS_FROM_OIL,
    CO2_EMISSIONS_FROM_OTHER_INDUSTRY,
    CO2_PER_GDP_KG_PER_PPP,
    CO2_PER_UNIT_ENERGY_KGCO2_PER_KILOWATT_HOUR,
    CEMENT_EMISSIONS_PER_CAPITA,
    COAL_EMISSIONS_PER_CAPITA,
    CONSUMPTION_BASED_CO2_PER_GDP_KG_PER_PPP,
    CUMULATIVE_CO2_EMISSIONS,
    CUMULATIVE_CEMENT_EMISSIONS,
    CUMULATIVE_COAL_EMISSIONS,
    CUMULATIVE_FLARING_EMISSIONS,
    CUMULATIVE_GAS_EMISSIONS,
    CUMULATIVE_OIL_EMISSIONS,
    CUMULATIVE_OTHER_INDUSTRY_EMISSIONS,
    EMISSIONS_EMBEDDED_IN_TRADE_PER_CAPITA,
    ENTITY,
    FLARING_EMISSIONS_PER_CAPITA,
    GAS_EMISSIONS_PER_CAPITA,
    OIL_EMISSIONS_PER_CAPITA,
    OTHER_EMISSIONS_PER_CAPITA,
    PER_CAPITA_CO2_EMISSIONS,
    PER_CAPITA_CONSUMPTION_BASED_CO2_EMISSIONS,
    SHARE_OF_CO2_EMISSIONS_EMBEDDED_IN_TRADE,
    SHARE_OF_GLOBAL_CO2_EMISSIONS,
    SHARE_OF_GLOBAL_CEMENT_EMISSIONS,
    SHARE_OF_GLOBAL_COAL_EMISSIONS,
    SHARE_OF_GLOBAL_CUMULATIVE_CO2_EMISSIONS,
    SHARE_OF_GLOBAL_CUMULATIVE_CEMENT_EMISSIONS,
    SHARE_OF_GLOBAL_CUMULATIVE_COAL_EMISSIONS,
    SHARE_OF_GLOBAL_CUMULATIVE_FLARING_EMISSIONS,
    SHARE_OF_GLOBAL_CUMULATIVE_GAS_EMISSIONS,
    SHARE_OF_GLOBAL_CUMULATIVE_OIL_EMISSIONS,
    SHARE_OF_GLOBAL_FLARING_EMISSIONS,
    SHARE_OF_GLOBAL_GAS_EMISSIONS,
    SHARE_OF_GLOBAL_OIL_EMISSIONS,
    "Year"
) as (
    select   
    PARSE_JSON(JSON_STRING):"Annual CO2 emissions"::VARCHAR AS Annual_CO2_emissions,      
    PARSE_JSON(JSON_STRING):"Annual CO2 growth (%)"::VARCHAR AS Annual_CO2_growth_percentage,
    PARSE_JSON(JSON_STRING):"Annual CO2 growth (abs)"::VARCHAR AS Annual_CO2_growth_abs,
    PARSE_JSON(JSON_STRING):"Annual consumption-based CO2 emissions"::VARCHAR AS Annual_consumption_based_CO2_emissions,
    PARSE_JSON(JSON_STRING):"CO2 emissions embedded in trade"::VARCHAR AS CO2_emissions_embedded_in_trade,
    PARSE_JSON(JSON_STRING):"CO2 emissions from bunkers"::VARCHAR AS CO2_emissions_from_bunkers,
    PARSE_JSON(JSON_STRING):"CO2 emissions from cement"::VARCHAR AS CO2_emissions_from_cement,
    PARSE_JSON(JSON_STRING):"CO2 emissions from coal"::VARCHAR AS CO2_emissions_from_coal,
    PARSE_JSON(JSON_STRING):"CO2 emissions from flaring"::VARCHAR AS CO2_emissions_from_flaring,
    PARSE_JSON(JSON_STRING):"CO2 emissions from gas"::VARCHAR AS CO2_emissions_from_gas,
    PARSE_JSON(JSON_STRING):"CO2 emissions from oil"::VARCHAR AS CO2_emissions_from_oil,
    PARSE_JSON(JSON_STRING):"CO2 emissions from other industry"::VARCHAR AS CO2_emissions_from_other_industry,
    PARSE_JSON(JSON_STRING):"CO2 per GDP (kg per $PPP)"::VARCHAR AS CO2_per_GDP_kg_per_PPP,
    PARSE_JSON(JSON_STRING):"CO2 per unit energy (kgCO2 per kilowatt-hour)"::VARCHAR AS CO2_per_unit_energy_kgCO2_per_kilowatt_hour,
    PARSE_JSON(JSON_STRING):"Cement emissions (per capita)"::VARCHAR AS Cement_emissions_per_capita,
    PARSE_JSON(JSON_STRING):"Coal emissions (per capita)"::VARCHAR AS Coal_emissions_per_capita,
    PARSE_JSON(JSON_STRING):"Consumption-based CO2 per GDP (kg per $PPP)"::VARCHAR AS Consumption_based_CO2_per_GDP_kg_per_PPP,
    PARSE_JSON(JSON_STRING):"Cumulative CO2 emissions"::VARCHAR AS Cumulative_CO2_emissions,
    PARSE_JSON(JSON_STRING):"Cumulative cement emissions"::VARCHAR AS Cumulative_cement_emissions,
    PARSE_JSON(JSON_STRING):"Cumulative coal emissions"::VARCHAR AS Cumulative_coal_emissions,
    PARSE_JSON(JSON_STRING):"Cumulative flaring emissions"::VARCHAR AS Cumulative_flaring_emissions,
    PARSE_JSON(JSON_STRING):"Cumulative gas emissions"::VARCHAR AS Cumulative_gas_emissions,
    PARSE_JSON(JSON_STRING):"Cumulative oil emissions"::VARCHAR AS Cumulative_oil_emissions,
    PARSE_JSON(JSON_STRING):"Cumulative other industry emissions"::VARCHAR AS Cumulative_other_industry_emissions,
    PARSE_JSON(JSON_STRING):"Emissions embedded in trade per capita"::VARCHAR AS Emissions_embedded_in_trade_per_capita,
    PARSE_JSON(JSON_STRING):"Entity"::VARCHAR AS Entity,
    PARSE_JSON(JSON_STRING):"Flaring emissions (per capita)"::VARCHAR AS Flaring_emissions_per_capita,
    PARSE_JSON(JSON_STRING):"Gas emissions (per capita)"::VARCHAR AS Gas_emissions_per_capita,
    PARSE_JSON(JSON_STRING):"Oil emissions (per capita)"::VARCHAR AS Oil_emissions_per_capita,
    PARSE_JSON(JSON_STRING):"Other emissions (per capita)"::VARCHAR AS Other_emissions_per_capita,
    PARSE_JSON(JSON_STRING):"Per capita CO2 emissions"::VARCHAR AS Per_capita_CO2_emissions,
    PARSE_JSON(JSON_STRING):"Per capita consumption-based CO2 emissions"::VARCHAR AS Per_capita_consumption_based_CO2_emissions,
    PARSE_JSON(JSON_STRING):"Share of CO2 emissions embedded in trade"::VARCHAR AS Share_of_CO2_emissions_embedded_in_trade,
    PARSE_JSON(JSON_STRING):"Share of global CO2 emissions"::VARCHAR AS Share_of_global_CO2_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cement emissions"::VARCHAR AS Share_of_global_cement_emissions,
    PARSE_JSON(JSON_STRING):"Share of global coal emissions"::VARCHAR AS Share_of_global_coal_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cumulative CO2 emissions"::VARCHAR AS Share_of_global_cumulative_CO2_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cumulative cement emissions"::VARCHAR AS Share_of_global_cumulative_cement_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cumulative coal emissions"::VARCHAR AS Share_of_global_cumulative_coal_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cumulative flaring emissions"::VARCHAR AS Share_of_global_cumulative_flaring_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cumulative gas emissions"::VARCHAR AS Share_of_global_cumulative_gas_emissions,
    PARSE_JSON(JSON_STRING):"Share of global cumulative oil emissions"::VARCHAR AS Share_of_global_cumulative_oil_emissions,
    PARSE_JSON(JSON_STRING):"Share of global flaring emissions"::VARCHAR AS Share_of_global_flaring_emissions,
    PARSE_JSON(JSON_STRING):"Share of global gas emissions"::VARCHAR AS Share_of_global_gas_emissions,
    PARSE_JSON(JSON_STRING):"Share of global oil emissions"::VARCHAR AS Share_of_global_oil_emissions,
    PARSE_JSON(JSON_STRING):"Year"::VARCHAR AS "Year"
    from EXERCISE_CO2_VS_TEMPERATURE.PSA.EMISSIONBYCOUNTRY
);